from django.urls import path

from web import views

urlpatterns = [
    path("", views.home, name="home"),
    path("projects/", views.projects_list, name="projects"),
    path("projects/<slug:slug>/", views.project_detail, name="project_detail"),
    path("ai-tools/pomelli-ai", views.pomelli, name="pomelli_ai"),
    path("ai-tools/pomeli-ai", views.pomelli),
    path("ai-tools/midjourney", views.midjourney, name="midjourney"),
    path("ai-tools/dall-e", views.dalle, name="dalle"),
    path("ai-tools/runwayml", views.runwayml, name="runwayml"),
    path("ai-tools/cursor", views.cursor_ai, name="cursor_ai"),
    path("ai-tools/github-copilot", views.github_copilot, name="github_copilot"),
    path("ai-tools/autogpt", views.autogpt, name="autogpt"),
    path("ai-tools/agentgpt", views.agentgpt, name="agentgpt"),
    path("ai-tools/google-gemini", views.google_gemini, name="google_gemini"),
    path("ai-tools/perplexity", views.perplexity, name="perplexity"),
    path("ai-tools/chatgpt", views.chatgpt, name="chatgpt"),
    path("ai-tools/jasper-ai", views.jasper_ai, name="jasper_ai"),
    path("ai-tools/copy-ai", views.copy_ai, name="copy_ai"),
    path("ai-tools/elevenlabs", views.elevenlabs, name="elevenlabs"),
    path("ai-tools/murf-ai", views.murf_ai, name="murf_ai"),
    path("ai-tools/otter-ai", views.otter_ai, name="otter_ai"),
    path("ai-tools/replit-ai", views.replit_ai, name="replit_ai"),
    path("ai-tools/adcreative-ai", views.adcreative_ai, name="adcreative_ai"),
    path("ai-tools/claude-ai", views.claude_ai, name="claude_ai"),
    path("ai-tools/codeium", views.codeium, name="codeium"),
    path("ai-tools/tabnine", views.tabnine, name="tabnine"),
    path("ai-tools/langchain", views.langchain, name="langchain"),
    path("ai-tools/crewai", views.crewai, name="crewai"),
    path("ai-tools/langgraph", views.langgraph, name="langgraph"),
    path("ai-tools/autogen", views.autogen, name="autogen"),
    path("ai-tools/smolagents", views.smolagents, name="smolagents"),
    path("ai-tools/openclaw", views.openclaw, name="openclaw"),
    path("ai-tools/category/<slug:category_slug>/", views.ai_tools_category, name="ai_tools_category"),
    path("ai-tools/", views.ai_tools_list, name="ai_tools"),
    path("tutorials/", views.tutorials, name="tutorials"),
    path("hackathons/", views.hackathons, name="hackathons"),
    path("contests/", views.contests, name="contests"),
]
